---
title: "Untitled"
author: "Yuliia Ilienko"
date: "2023-12-30"
output: html_document
---

```{r}
### Preparation of the Environment ####

# Clear environment
remove(list = ls())

# Create list with needed libraries
pkgs <- c("readr", "dplyr", "reticulate", "ggplot2", "Metrics")

# Load each listed library and check if it is installed and install if necessary
for (pkg in pkgs) {
  if (!require(pkg, character.only = TRUE)) {
    install.packages(pkg)
    library(pkg, character.only = TRUE)
  }
}

```



```{r}
### Data Import ####

# Read relevant data
sales_data <- read_csv("train.csv")

test_data <- read_csv("test.csv")

# Create Trainingsdatensatz vom 01.07.2013 bis 31.07.2017
train_data <- sales_data %>%
  filter(Datum >= as.Date("2013-07-01") & Datum <= as.Date("2017-07-31"))

# Create Validierungsdatensatz vom 01.08.2017 bis 31.07.2018
validation_data <- sales_data %>%
  filter(Datum >= as.Date("2017-08-01") & Datum <= as.Date("2018-07-31"))



#Kiwo Daten
kiwo_data <- read.csv("kiwo.csv")
# Convert "Datum" column to Date format
kiwo_data$Datum <- as.Date(kiwo_data$Datum, format = "%Y-%m-%d")

#Ferien Daten
ferien_data <- read_csv("updated_ferien.csv")

#Wetter Daten
weather_data <- read_csv("wetter.csv")

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r}
train_data_combined <- train_data %>%
  left_join(kiwo_data, by = "Datum") %>%
   left_join(weather_data, by = "Datum") %>%
  left_join(ferien_data, by = "Datum")

View(train_data_combined)

# Join für validation_data
validation_data_combined <- validation_data %>%
  left_join(kiwo_data, by = "Datum") %>%
  left_join(weather_data, by = "Datum") %>%
  left_join(ferien_data, by = "Datum")

# Join für test_data
test_data_combined <- test_data %>%
  left_join(kiwo_data, by = "Datum") %>%
  left_join(weather_data, by = "Datum") %>%
  left_join(ferien_data, by = "Datum")




```

```{r}
# Create a vector of public holidays for Schleswig-Holstein (2013-2018), including Dec 24th and Dec 31st
schleswig_holstein_feiertage <- as.Date(c(
  "2013-01-01", "2013-03-29", "2013-04-01", "2013-05-01", "2013-05-09",
  "2013-05-20", "2013-10-03", "2013-12-25", "2013-12-26", "2013-12-24", "2013-12-31",
  "2014-01-01", "2014-04-18", "2014-04-21", "2014-05-01", "2014-05-29",
  "2014-06-09", "2014-10-03", "2014-12-25", "2014-12-26", "2014-12-24", "2014-12-31",
  "2015-01-01", "2015-04-03", "2015-04-06", "2015-05-01", "2015-05-14",
  "2015-05-25", "2015-10-03", "2015-12-25", "2015-12-26", "2015-12-24", "2015-12-31",
  "2016-01-01", "2016-03-25", "2016-03-28", "2016-05-01", "2016-05-05",
  "2016-05-16", "2016-10-03", "2016-12-25", "2016-12-26", "2016-12-24", "2016-12-31",
  "2017-01-01", "2017-04-14", "2017-04-17", "2017-05-01", "2017-05-25",
  "2017-06-05", "2017-10-03", "2017-12-25", "2017-12-26", "2017-12-24", "2017-12-31",
  "2018-01-01", "2018-03-30", "2018-04-02", "2018-05-01", "2018-05-10",
  "2018-05-21", "2018-10-03", "2018-12-25", "2018-12-26", "2018-12-24", "2018-12-31",
  "2019-01-01", "2019-04-19", "2019-04-22", "2019-05-01", "2019-05-30", "2019-06-10"
))


train_data_combined <- train_data_combined %>%
  mutate(IsFeiertag = ymd(Datum) %in% schleswig_holstein_feiertage)

# Add a holiday column to validation_data
validation_data_combined <- validation_data_combined %>%
  mutate(IsFeiertag = ymd(Datum) %in% schleswig_holstein_feiertage)

# Add a holiday column to test_data
test_data_combined <- test_data_combined %>%
  mutate(IsFeiertag = ymd(Datum) %in% schleswig_holstein_feiertage)



```
